language: python
python:
  - "3.6.4"
  
# command to install dependencies

before_script:
- psql -c 'create database challenge3;' -U postgres

before_install:
- pip install pytest pytest-cov
- pip install coveralls
install:
  - pip install -r requirements.txt
  
script:
  - pytest
after_success:
  - coverage run -m pytest
